[[permission]]
identifier = "allow-net"
description = "Allows connecting to dadi and storing provisioning credentials."
commands.allow = [
  "mesh_start",
  "mesh_stop",
  "mesh_status",
  "mesh_port",
  "mesh_load_credentials",
  "mesh_save_credentials",
  "mesh_clear_credentials"
]
